# Generated by Django 5.2.3 on 2025-07-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='player_type',
            field=models.CharField(choices=[('direct', 'Direct Player'), ('iframe', 'Iframe Player')], default='direct', help_text='The preferred player type for this video (direct link or iframe).', max_length=10),
        ),
    ]
