# Generated by Django 5.2.3 on 2025-07-14 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_tag_options_alter_tag_name_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videolike',
            index=models.Index(fields=['user', 'video'], name='videolike_user_video_idx'),
        ),
        migrations.AddIndex(
            model_name='videolike',
            index=models.Index(fields=['video', 'created_at'], name='videolike_video_crt_idx'),
        ),
    ]
