# Generated by Django 5.2.3 on 2025-06-25 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('users', '0002_profile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_bookmark_collection',
            field=models.ForeignKey(blank=True, help_text='Default collection to pre-select when creating a new bookmark.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.collection'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_bookmark_orientation',
            field=models.CharField(blank=True, choices=[('straight', 'Straight'), ('gay', 'Gay'), ('bi', 'Bi'), ('trans', 'Trans'), ('sfw', 'SFW')], help_text='Default orientation to pre-fill when creating a new bookmark.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_on_follow',
            field=models.BooleanField(default=True, help_text='Receive a notification when someone starts following you.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_on_new_bookmark_from_followed_user',
            field=models.BooleanField(default=True, help_text='Receive a notification when a user you follow creates a new public bookmark.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_on_own_video_bookmarked',
            field=models.BooleanField(default=True, help_text='Receive a notification when someone bookmarks one of your videos.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_on_own_video_liked',
            field=models.BooleanField(default=True, help_text='Receive a notification when someone likes one of your videos.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['-created_at'], name='bm_created_at_desc_idx'),
        ),
    ]
