# Generated by Django 5.2.3 on 2025-07-10 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bm_vid_usr_crt_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bm_channel_crt_idx',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profile_user_idx'),
        ),
    ]
